-- TÜM VERİLER "TARİŞ" MARKASI ÖZELİNDEDİR

-- ÖZET sayfası: TOPLAM CİRO-TOPLAM SATIŞ ADEDİ-TOPLAM SİPARİŞ SAYISI
SELECT 
SUM(LINETOTAL)TOPLAM_CIRO, 
SUM(AMOUNT)TOPLAM_SATIS_ADEDI, 
COUNT(ORDERID)TOPLAM_SIPARIS_ADEDI 
FROM etrade2.dbo.ORDERDETAILS OD
JOIN etrade2.dbo.ITEMS I
ON I.ID = OD.ITEMID
WHERE BRAND='TARIS';

-- ÖZET sayfası: TOPLAM MÜŞTERİ SAYISI, MÜŞTERİ sayfası: TEKİL MÜŞTERİ SAYISI
SELECT 
COUNT(USERID)TOP_MUSTERI_SAYISI, 
COUNT(DISTINCT(USERID))TEKIL_MUSTERI_SAYISI 
FROM etrade2.dbo.ORDERS O
JOIN etrade2.dbo.ORDERDETAILS OD
ON O.ID = OD.ORDERID 
JOIN etrade2.dbo.ITEMS I
ON I.ID = OD.ITEMID
WHERE BRAND='TARIS';

-- MÜŞTERİ sayfası: KADIN / ERKEK MÜŞTERİ SAYISI
SELECT
  CASE
    WHEN U.GENDER = 'K' THEN 'KADIN'
    ELSE 'ERKEK'
  END AS GENDER, 
  COUNT(USERID)TOP_MUSTERI_SAYISI,
  COUNT(DISTINCT USERID)TEKIL_MUSTERI_SAYISI
FROM etrade2.dbo.ORDERS O
JOIN etrade2.dbo.ORDERDETAILS OD 
ON O.ID = OD.ORDERID 
JOIN etrade2.dbo.ITEMS I
ON I.ID = OD.ITEMID
JOIN etrade2.dbo.USERS U
ON O.USERID = U.ID 
WHERE BRAND='TARIS'
GROUP BY
  CASE
    WHEN U.GENDER = 'K' THEN 'KADIN'
    ELSE 'ERKEK'
  END

-- MÜŞTERİ sayfası: istanbul ilk 10 müşteri, TOPLAM CİRO'ya göre sıralanmış (Azalan)
SELECT TOP 10
    U.NAMESURNAME,
    SUM(OD.LINETOTAL)TOPLAM_CIRO,
    SUM(OD.AMOUNT)TOPLAM_SATIS_ADEDI,
    COUNT(DISTINCT OD.ORDERID)TOPLAM_SIPARIS_ADEDI
FROM etrade2.dbo.ORDERDETAILS OD
JOIN etrade2.dbo.ORDERS O ON O.ID = OD.ORDERID
JOIN etrade2.dbo.USERS U ON U.ID = O.USERID
JOIN etrade2.dbo.ADDRESS A ON A.ID = O.ADDRESSID
JOIN etrade2.dbo.ITEMS I ON I.ID = OD.ITEMID
WHERE A.CITYID = 34
AND I.BRAND = 'TARIS'  
GROUP BY U.NAMESURNAME
ORDER BY SUM(OD.LINETOTAL) DESC;

-- -- MÜŞTERİ sayfası: YAŞ GRUBU'na göre TOPLAM CİRO 
SELECT
  CASE
    WHEN U.AGE <= 20 THEN 'GENÇ'
    WHEN U.AGE <= 35 THEN 'YETİŞKİN'
    WHEN U.AGE <= 55 THEN 'ORTA YAŞ'
    ELSE 'YAŞLI'
  END AS YAS_GRUBU,
  SUM(OD.LINETOTAL)TOPLAM_CIRO
FROM etrade2.dbo.ORDERDETAILS OD
JOIN etrade2.dbo.ITEMS I ON I.ID = OD.ITEMID
JOIN etrade2.dbo.ORDERS O ON O.ID = OD.ORDERID
JOIN etrade2.dbo.USERS U ON U.ID = O.USERID
WHERE I.BRAND = 'TARIS'
GROUP BY
  CASE
    WHEN U.AGE <= 20 THEN 'GENÇ'
    WHEN U.AGE <= 35 THEN 'YETİŞKİN'
    WHEN U.AGE <= 55 THEN 'ORTA YAŞ'
    ELSE 'YAŞLI'
  END
ORDER BY TOPLAM_CIRO DESC;




